name: Test and Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - "3306:3306"
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    # Obtener el c√≥digo del repo
    - uses: actions/checkout@v4

    # Instalar PHP 8.3 con extensiones
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl, pdo_mysql, bcmath
        coverage: none

    # Crear .env si no existe
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # Instalar dependencias de Laravel
    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist --no-scripts --no-progress

    # Configurar variables de entorno
    - name: Configure Laravel Environment
      run: |
        php artisan key:generate
        sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env
        sed -i 's/DB_DATABASE=.*/DB_DATABASE=testing/' .env
        sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env
        sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=root/' .env

    # Permisos
    - name: Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Esperar MySQL
    - name: Wait for MySQL to be Ready
      run: |
        for i in {1..30}; do
          mysqladmin ping -h 127.0.0.1 -uroot -proot && break
          echo "Esperando MySQL..."
          sleep 2
        done

    # Migraciones
    - name: Run Migrations
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: testing
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan migrate --force

    # Tests
    - name: Run Tests
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: testing
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan test

    # Login GHCR
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build + Push Docker
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/jmdza24/gestortickets:latest

